using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HoiThao.Web.Models
{
    public class aseanViewModel
    {
        public decimal k { get; set; }
        public string id { get; set; }
        public Nullable<bool> speaker { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string company { get; set; }
        public string department { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string institutio { get; set; }
        public string makh { get; set; }
        public Nullable<System.DateTime> dangky { get; set; }
        public string tel { get; set; }
        public string title { get; set; }
        public Nullable<bool> code { get; set; }
        public string currency { get; set; }
        public string group { get; set; }
        public string note { get; set; }
        public Nullable<bool> invited { get; set; }
        public string payment { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> bankfee { get; set; }
        public Nullable<decimal> totala { get; set; }
        public Nullable<decimal> totalb { get; set; }
        public Nullable<decimal> grandtotal { get; set; }
        public string Hotel { get; set; }
        public string HotelCheckin { get; set; }
        public string HotelCheckout { get; set; }
        public string HotelPrice { get; set; }
        public string HotelDon { get; set; }
        public string HotelTien { get; set; }
        public string HotelBookingInf { get; set; }
        public Nullable<bool> bongsen { get; set; }
        public string cibongsen { get; set; }
        public string cobongsen { get; set; }
        public string bs_rate { get; set; }
        public string bsbk { get; set; }
        public Nullable<bool> kimdo { get; set; }
        public string cikimdo { get; set; }
        public string cokimdo { get; set; }
        public string kd_rate { get; set; }
        public string kdbk { get; set; }
        public Nullable<bool> winsor { get; set; }
        public string ciwinsor { get; set; }
        public string cowinsor { get; set; }
        public string ws_rate { get; set; }
        public string wsbk { get; set; }
        public Nullable<bool> sofitel { get; set; }
        public string cisofitel { get; set; }
        public string cosofitel { get; set; }
        public string sf_rate { get; set; }
        public string sfbk { get; set; }
        public Nullable<bool> rex { get; set; }
        public string cirex { get; set; }
        public string corex { get; set; }
        public string rex_rate { get; set; }
        public string rexbk { get; set; }
        public Nullable<bool> caravelle { get; set; }
        public string cicaravel { get; set; }
        public string cocaravel { get; set; }
        public string ca_rate { get; set; }
        public string cabk { get; set; }
        public Nullable<bool> sheraton { get; set; }
        public string cisheraton { get; set; }
        public string cosheraton { get; set; }
        public string sh_rate { get; set; }
        public string shbk { get; set; }
        public string htlother { get; set; }
        public Nullable<System.DateTime> city { get; set; }
        public Nullable<decimal> cityper { get; set; }
        public Nullable<System.DateTime> cuchi { get; set; }
        public Nullable<decimal> cuchiper { get; set; }
        public Nullable<System.DateTime> saigon { get; set; }
        public Nullable<decimal> saigonper { get; set; }
        public Nullable<System.DateTime> golf { get; set; }
        public Nullable<decimal> golfper { get; set; }
        public Nullable<System.DateTime> mekong { get; set; }
        public Nullable<decimal> mekongper { get; set; }
        public Nullable<System.DateTime> phanthiet { get; set; }
        public Nullable<decimal> ptper { get; set; }
        public string central { get; set; }
        public Nullable<decimal> ctper { get; set; }
        public string wonder { get; set; }
        public Nullable<decimal> wdper { get; set; }
        public Nullable<System.DateTime> deepmk { get; set; }
        public Nullable<decimal> deepmkper { get; set; }
        public Nullable<System.DateTime> nhatrang { get; set; }
        public Nullable<decimal> nhatrangsk { get; set; }
        public Nullable<System.DateTime> kpc { get; set; }
        public Nullable<decimal> kpcsk { get; set; }
        public Nullable<System.DateTime> lao { get; set; }
        public Nullable<decimal> laosk { get; set; }
        public string ydepdate { get; set; }
        public string ydeproute { get; set; }
        public Nullable<decimal> ydepperson { get; set; }
        public string cdepdate { get; set; }
        public string cdeproute { get; set; }
        public Nullable<decimal> cdepperson { get; set; }
        public string yretdate { get; set; }
        public string yretroute { get; set; }
        public Nullable<decimal> yretperson { get; set; }
        public string cretdate { get; set; }
        public string cretroute { get; set; }
        public Nullable<decimal> cretperson { get; set; }
        public Nullable<decimal> bus_ah { get; set; }
        public Nullable<decimal> bus_ha { get; set; }
        public string car_ah { get; set; }
        public string sharecarah { get; set; }
        public string car_ha { get; set; }
        public string sharecarha { get; set; }
        public Nullable<decimal> bschinh { get; set; }
        public Nullable<decimal> giachinh { get; set; }
        public Nullable<decimal> bsnoitru { get; set; }
        public Nullable<decimal> gianoitru { get; set; }
        public Nullable<decimal> dikem { get; set; }
        public Nullable<decimal> giadikem { get; set; }
        public Nullable<decimal> hoithao1 { get; set; }
        public Nullable<decimal> giaht1 { get; set; }
        public Nullable<decimal> hoithaogp1 { get; set; }
        public Nullable<decimal> giahtgp1 { get; set; }
        public Nullable<decimal> hoithao2 { get; set; }
        public Nullable<decimal> giaht2 { get; set; }
        public Nullable<decimal> hoithaogp2 { get; set; }
        public Nullable<decimal> giahtgp2 { get; set; }
        public Nullable<decimal> hoithao3 { get; set; }
        public Nullable<decimal> giaht3 { get; set; }
        public Nullable<decimal> hoithaogp3 { get; set; }
        public Nullable<decimal> giahtgp3 { get; set; }
        public Nullable<decimal> allergy { get; set; }
        public Nullable<decimal> giaallergy { get; set; }
        public string at { get; set; }
        public string afno { get; set; }
        public string dt { get; set; }
        public string dfno { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public string mop { get; set; }
        public string cardnumber { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string vatbill { get; set; }
        public string descript { get; set; }
        public string taxcode { get; set; }
    }
}